### ISSUE TITLE
Automatic PRs should use a proxy when referring to PRs

### ISSUE THREAD

**Issue by oliviertassinari** [snyk/user-docs#357]
Snyk should use a proxy when referencing other PRs on GitHub. This spam all the open source projects:

<img width="877" alt="SCR-20240822-bojx" src="https://github.com/user-attachments/assets/38f71e36-30d4-477d-8161-f337a83b4b32">

Source of the screenshot: https://github.com/mui/mui-x/pull/13350

Renovate uses togithub.com https://github.com/renovatebot/renovate/discussions/10796
Dependabot uses redirect.github.com

Could Synk do the same? This seems much better. Thanks

cc @TashaTBaker I see you have been making changes to https://docs.snyk.io/scan-using-snyk/pull-requests/snyk-fix-pull-or-merge-requests/create-automatic-prs-for-new-fixes lately. Could you help me bring this to the attention of the right team?

**Comment by TashaTBaker** [comment]
Hi Olivier,
Thank you for your comments here. I will direct this to the right team internally so they can have a look.

**Comment by Jdunsby** [comment]
Hi Olivier

Thanks for flagging this issue. It seems that it originated in a PR where the banner image had been incorrectly formatted, so the markdown (including GitHub URL) was displayed instead of the image.

We've since fixed this issue with the default PR templates, so the banner URL isn't present, and you won't see any further GH URLs in those PRs using the default templates.

I've also made sure that we have redirect Github URLs in place for PRs that are using a custom templates, so this issue shouldn't occur in those PRs either.

Please let us know if you spot any recurrence or other issues with Snyk. Your feedback is much appreciated.

**Comment by oliviertassinari** [comment]
@Jdunsby The problem is still present. I didn't notice behavioral changes. For example in https://github.com/prathik2401/my-portfolio/pull/64. Those are still direct URLs:

<img width="712" alt="SCR-20240921-pgtq" src="https://github.com/user-attachments/assets/7e014743-4094-4443-9714-d5c2046759f8">

I would expect this diff:

```diff
-https://github.com/mui/material-ui/pull/43488
+https://redirect.github.com/mui/material-ui/pull/43488
```

**Comment by oliviertassinari** [comment]
Any update? For example https://github.com/mui/mui-x/pull/14170. It's a shitshow on this PR.
